In [2]:
print("Hello World")

Hello World


# This is Introduction to tensor

In [3]:
import torch 
print(torch.__version__)

2.11.0+cu128


In [4]:
if torch.cuda.is_available():
    print("GPU is available")
    print(torch.cuda.get_device_name(0)) # to find the divice name of the GPU
else:
    print("GPU is not available")



GPU is available
Tesla T4


# Creating a Tensor

In [5]:
# using empty 
tensor = torch.empty(2,3) # creates a 2x3 matrix with random values
# it creates an empty tensor and the values which it returns are the previously stored values in the memory location. So it is not initialized with any values.
print(tensor)

tensor([[9.8171e-22, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [6]:
# using zeros
tensor = torch.zeros(2,3) # creates a 2x3 matrix with all values as 0
print(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# using ones
tensor = torch.ones(2,3) # creates a 2x3 matrix with all values as 1
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
# using eye
tensor = torch.eye(3) # creates a 3x3 identity matrix
print(tensor)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [9]:
# using rand 
tensor = torch.rand(2,3) # creates a 2x3 matrix with random values between 0 and 1
print(tensor) 
"""
     the problem with rand is that it generats random values every time we run it.
     so if we want to generate the same random values every time we run it, we can use the seed function.

"""


tensor([[0.3056, 0.1071, 0.0076],
        [0.3002, 0.0882, 0.0200]])


'\n     the problem with rand is that it generats random values every time we run it.\n     so if we want to generate the same random values every time we run it, we can use the seed function.\n\n'

In [10]:
# using seed 
torch.manual_seed(100) # sets the seed for generating random numbers
tensor = torch.rand(2,3) # creates a 2x3 matrix with random values between 0 and 1
print(tensor) 

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [11]:
torch.manual_seed(100) # sets the seed for generating random numbers
tensor = torch.rand(2,3) # creates a 2x3 matrix with same random values 
print(tensor)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [12]:
# using tensor 
tensor = torch.tensor([[1,2,3],[4,5,6]]) # creates a 2x3 matrix with the given values
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


### some other meathodes


In [13]:
# using arange
tensor = torch.arange(0,10,2) # creates a 1D tensor with values from 0 to 10 with a step of 2
print(tensor)
# using linspace
tensor = torch.linspace(0,10,5) # creates a 1D tensor with 5 values from 0 to 10
print(tensor)
# using full
tensor = torch.full((2,3),7) # creates a 2x3 matrix with all values as 7
print(tensor)

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([[7, 7, 7],
        [7, 7, 7]])


#### Finding the shape of tensor

In [14]:
x = torch.tensor([1,2,3])
print(x.shape)


torch.Size([3])


In [15]:
# creating a new tensor with the same shape as x
y = torch.zeros_like(x) # creates a tensor with the same shape as x and all values as 0
print(y)
y = torch.ones_like(x) # creates a tensor with the same shape as x and all values as 1
print(y)
#y = torch.rand_like(x) # creates a tensor with the same shape as x and random values between 0 and 1
#print(y)
y = torch.full_like(x,7) # creates a tensor with the same shape as x and all values as 7
print(y)
y = torch.empty_like(x) # creates a tensor with the same shape as x and all values as 1 in the diagonal and 0 elsewhere
print(y)

"""
    # We will see why rand_like, arrange_like and eye_like are not working
    # it is because they generate float values where as x is an integer data type tensor
    # So we explecetly need to tell that we want the float type values
"""

tensor([0, 0, 0])
tensor([1, 1, 1])
tensor([7, 7, 7])
tensor([      488897954,               0, 111544602293100])


'\n    # We will see why rand_like, arrange_like and eye_like are not working\n    # it is because they generate float values where as x is an integer data type tensor\n    # So we explecetly need to tell that we want the float type values\n'

# Reshaping the tensor

In [35]:
x = torch.arange(1,21)
print(x, x.shape, sep = "\n")
x.reshape((4,5))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
torch.Size([20])


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [40]:
torch.manual_seed(50)
x = torch.rand((3,4))
y = torch.eye(4)
print(x, y, sep = "\n")
y.reshape(2,8)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877],
        [0.5927, 0.9634, 0.1230, 0.4048]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


tensor([[1., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 1.]])

# data type of a tensor

In [16]:
#
x.dtype

torch.int64

In [17]:
# how to specify the data type of the tensor
tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float16)
print(tensor, tensor.dtype)
# how to convert the dtype of a tensor
x.to(torch.float32) # don't changes the original tensor
print("x:   ",x,"\n",x.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16) torch.float16
x:    tensor([1, 2, 3]) 
 torch.int64


In [18]:
x = torch.tensor([1, 2, 3]) # Starts as int64

# Reassign the result to update x
x = x.to(torch.float32)

print("x:   ", x, "\n", x.dtype)
# Output:
# x:    tensor([1., 2., 3.]) 
# torch.float32

x:    tensor([1., 2., 3.]) 
 torch.float32


In [19]:
# soln to our previous problem
x = torch.tensor([1, 2, 3])
print("X : ",x)
y = torch.rand_like(x, dtype = torch.float32) # we just need to specify the data type
print(y)

X :  tensor([1, 2, 3])
tensor([0.2627, 0.0428, 0.2080])


# Operations on tensor

### 1) scalar operation

In [20]:
# addition
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
print(x + 2)
print( x - 1)
print(x * 2)
print(x / 2)
print(x // 2)
print(x % 2)

tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [22]:
# operation between two tensor
t1 = torch.full((2,2), 8)
t2 = torch.full((2,2),2)
print(t1)
print(t2)

tensor([[8, 8],
        [8, 8]])
tensor([[2, 2],
        [2, 2]])


In [23]:
# add 
print(t1 + t2)
# sub 
print(t1 - t2)
# mul
print(t1 * t2)
# div
print(t1/t2)
# power 
print(t1**t2)
# mod 
print(t1%t2)

tensor([[10, 10],
        [10, 10]])
tensor([[6, 6],
        [6, 6]])
tensor([[16, 16],
        [16, 16]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[64, 64],
        [64, 64]])
tensor([[0, 0],
        [0, 0]])


In [42]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
c = torch.tensor([7,8,9])
y = torch.vstack((a,b,c))
y

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
# abslout
c = torch.tensor([-1,-2,3,-4])
c.abs()

tensor([1, 2, 3, 4])

In [56]:
# negative
torch.neg(c)

tensor([ 1,  2, -3,  4])

In [58]:
# round     
d = torch.tensor([1.2,3.2,4,3,5.6])
torch.round(d)

tensor([1., 3., 4., 3., 6.])

In [59]:
# ceil
torch.ceil(d)

tensor([2., 4., 4., 3., 6.])

In [60]:
# floor
torch.floor(d)

tensor([1., 3., 4., 3., 5.])

In [62]:
# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2., 3., 3., 3., 3.])

# Reduction 

In [75]:
torch.manual_seed(30)
e = torch.randint(size = (2,3), low = 0, high = 10, dtype= torch.float)
print(e)
# sum 
print("Sum", torch.sum(e), e.sum())

# sum along columns
print("Sum alog conumns keeping the dimension",torch.sum(e, dim = 0, keepdim= True))

# sum along rows 
print("Sum along Rows: ", torch.sum(e, dim = 1, keepdim= True), e.sum(dim=1, keepdim= True), sep="\n")

tensor([[7., 7., 7.],
        [3., 6., 4.]])
Sum tensor(34.) tensor(34.)
Sum alog conumns keeping the dimension tensor([[10., 13., 11.]])
Sum along Rows: 
tensor([[21.],
        [13.]])
tensor([[21.],
        [13.]])


In [77]:
# mean median
print("Sum", torch.mean(e), e.mean())

# mean along columns
print("mean alog conumns keeping the dimension",torch.mean(e, dim = 0, keepdim= True))

# mean along rows 
print("mean along Rows: ", torch.mean(e, dim = 1, keepdim= True), e.mean(dim=1, keepdim= True), sep="\n")


Sum tensor(5.6667) tensor(5.6667)
mean alog conumns keeping the dimension tensor([[5.0000, 6.5000, 5.5000]])
mean along Rows: 
tensor([[7.0000],
        [4.3333]])
tensor([[7.0000],
        [4.3333]])


In [79]:
# max min 
print(e.max())
print()
print(e.max(dim=0, keepdim= True))
print()
print(e.max(dim=1, keepdim=True))

tensor(7.)

torch.return_types.max(
values=tensor([[7., 7., 7.]]),
indices=tensor([[0, 0, 0]]))

torch.return_types.max(
values=tensor([[7.],
        [6.]]),
indices=tensor([[0],
        [1]]))


In [81]:
# std
print(torch.std(e))

# variance
torch.var(e)

tensor(1.7512)


tensor(3.0667)

In [82]:
torch.argmax(e)

tensor(0)

In [83]:
torch.argmin(e)

tensor(3)

# Matrix operation

In [84]:
f = torch.randint(size = (2,3), low = 0, high = 4)
g = torch.randint(size = (3,4), low = 0, high = 4)

print(g)
print(f)


tensor([[3, 1, 3, 3],
        [1, 1, 1, 1],
        [3, 2, 2, 0]])
tensor([[3, 2, 1],
        [3, 1, 2]])


In [85]:
torch.matmul(f,g)

tensor([[14,  7, 13, 11],
        [16,  8, 14, 10]])

In [86]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])

torch.dot(v1,v2)

tensor(11)

In [87]:
# transpose 
print(f)
torch.transpose(f, 0,1)

tensor([[3, 2, 1],
        [3, 1, 2]])


tensor([[3, 3],
        [2, 1],
        [1, 2]])

In [88]:
# determinant 
h = torch.randint(size = (3,3), low = 0, high = 10, dtype= torch.float)
print(h)
torch.det(h)

tensor([[2., 2., 2.],
        [4., 4., 8.],
        [5., 0., 9.]])


tensor(40.)

In [89]:
h.det()

tensor(40.)

In [90]:
# inverse
torch.inverse(h)

tensor([[ 0.9000, -0.4500,  0.2000],
        [ 0.1000,  0.2000, -0.2000],
        [-0.5000,  0.2500, -0.0000]])

In [91]:
# comparision 
print(a,b,c, sep="\n")

print(a>b)
print(a<b)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([-1, -2,  3, -4])
tensor([False, False, False])
tensor([True, True, True])


# Special Functions

In [97]:
k = torch.randint(size=(2,3), low = 0, high = 4, dtype = torch.float)
k

tensor([[2., 3., 2.],
        [1., 0., 3.]])

In [101]:
# log
print(torch.log(k))
print(k.log())

# exp
print(torch.exp(k))
print(k.exp())

# sqrt
print(torch.sqrt(k))

# sigmoid
print(k.sigmoid())

# softmax
print(k.softmax(dim = 1)) ## row wise
print(k.softmax(dim= 0)) ## column wose

# relu
print(k.relu())

tensor([[0.6931, 1.0986, 0.6931],
        [0.0000,   -inf, 1.0986]])
tensor([[0.6931, 1.0986, 0.6931],
        [0.0000,   -inf, 1.0986]])
tensor([[ 7.3891, 20.0855,  7.3891],
        [ 2.7183,  1.0000, 20.0855]])
tensor([[ 7.3891, 20.0855,  7.3891],
        [ 2.7183,  1.0000, 20.0855]])
tensor([[1.4142, 1.7321, 1.4142],
        [1.0000, 0.0000, 1.7321]])
tensor([[0.8808, 0.9526, 0.8808],
        [0.7311, 0.5000, 0.9526]])
tensor([[0.2119, 0.5761, 0.2119],
        [0.1142, 0.0420, 0.8438]])
tensor([[0.7311, 0.9526, 0.2689],
        [0.2689, 0.0474, 0.7311]])
tensor([[2., 3., 2.],
        [1., 0., 3.]])


# Inplace Operation

In [103]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m,"\n",n)

tensor([[0.5232, 0.9378, 0.1448],
        [0.9291, 0.1173, 0.8549]]) 
 tensor([[0.6341, 0.4991, 0.5158],
        [0.8220, 0.2750, 0.4322]])


In [104]:
m.add_(n)

tensor([[1.1572, 1.4369, 0.6606],
        [1.7510, 0.3923, 1.2871]])

In [105]:
m

tensor([[1.1572, 1.4369, 0.6606],
        [1.7510, 0.3923, 1.2871]])

In [108]:
torch.relu_(m)

tensor([[1.1572, 1.4369, 0.6606],
        [1.7510, 0.3923, 1.2871]])

# Copying a Tensor

In [117]:
torch.manual_seed(5)
a = torch.rand(2,3)
a

tensor([[0.8303, 0.1261, 0.9075],
        [0.8199, 0.9201, 0.1166]])

In [118]:
b = a
b

tensor([[0.8303, 0.1261, 0.9075],
        [0.8199, 0.9201, 0.1166]])

In [119]:
a[0][0] = 0
a

tensor([[0.0000, 0.1261, 0.9075],
        [0.8199, 0.9201, 0.1166]])

In [120]:
b

tensor([[0.0000, 0.1261, 0.9075],
        [0.8199, 0.9201, 0.1166]])

In [121]:
b = a.clone()
a,b

(tensor([[0.0000, 0.1261, 0.9075],
         [0.8199, 0.9201, 0.1166]]),
 tensor([[0.0000, 0.1261, 0.9075],
         [0.8199, 0.9201, 0.1166]]))

In [122]:
a[0][0]= 10
a, b

(tensor([[10.0000,  0.1261,  0.9075],
         [ 0.8199,  0.9201,  0.1166]]),
 tensor([[0.0000, 0.1261, 0.9075],
         [0.8199, 0.9201, 0.1166]]))

# Pushing tensor on gpu

In [140]:
x = torch.randn(3, 4)

print("Before moving:", x.device)

# 1. Define the device (uses GPU if available, otherwise CPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 2. Move your data (your existing code)
x = x.to(device) # or x = x.cuda() if torch.cuda.is_available() else x.cpu()

print("After moving:", x.device)

Before moving: cpu
After moving: cuda:0


In [142]:
import time
# Define the size of the matrices
size = 10000 # Large size for performance comparison
# Create random matrices on CPU
matrix_cpu1 = torch.randn(size,
size)
matrix_cpu2 = torch.randn(size,
size)
# Measure time on CPU
start_time = time.time()
result_cu = torch.matmul(matrix_cpu1, matrix_cpu2) # Matrix multiplication on CPU
cpu_time = time. time () - start_time
print (f"Time on CPU: {cpu_time:.4f} seconds")
# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')
# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize()
# Ensure all GPU operations are complete
gpu_time = time.time() - start_time

Time on CPU: 16.7861 seconds


In [144]:
print(gpu_time)

0.8009037971496582


# Reshaping a tensor

In [148]:
x = torch.ones((1,2,3))
print(x)
# flattan
print("flattan ",x.flatten())

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])
flattan  tensor([1., 1., 1., 1., 1., 1.])


In [149]:
x.reshape(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [153]:
x.permute(1,0,2).shape

torch.Size([2, 1, 3])

In [154]:
# unsqueeze 
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [156]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [157]:
# squeeze 
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# NumPy and PyTorch

In [158]:
import numpy as np

In [159]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [160]:
b = a.numpy()

In [161]:
type(b)

numpy.ndarray

In [162]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [163]:
b = torch.from_numpy(a)
type(b)

torch.Tensor