In [ ]:
print("Hello")

Hello


# This is Introduction to tensor

In [ ]:
import torch 
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
else:
    print("GPU is not available")

torch.cuda.get_device_name(0) # to find the divice name of the GPU

GPU is available


'Tesla T4'

# Creating a Tensor

In [ ]:
# using empty 
tensor = torch.empty(2,3) # creates a 2x3 matrix with random values
# it creates an empty tensor and the values which it returns are the previously stored values in the memory location. So it is not initialized with any values.
print(tensor)

tensor([[3619.4844,    0.0000, 3650.8750],
        [   0.0000,    0.0000,    0.0000]])


In [ ]:
# using zeros
tensor = torch.zeros(2,3) # creates a 2x3 matrix with all values as 0
print(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# using ones
tensor = torch.ones(2,3) # creates a 2x3 matrix with all values as 1
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# using eye
tensor = torch.eye(3) # creates a 3x3 identity matrix
print(tensor)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
# using rand 
tensor = torch.rand(2,3) # creates a 2x3 matrix with random values between 0 and 1
print(tensor) 
"""
     the problem with rand is that it generats random values every time we run it.
     so if we want to generate the same random values every time we run it, we can use the seed function.

"""


tensor([[0.4416, 0.1307, 0.3462],
        [0.7727, 0.5978, 0.3277]])


'\n     the problem with rand is that it generats random values every time we run it.\n     so if we want to generate the same random values every time we run it, we can use the seed function.\n\n'

In [ ]:
# using seed 
torch.manual_seed(100) # sets the seed for generating random numbers
tensor = torch.rand(2,3) # creates a 2x3 matrix with random values between 0 and 1
print(tensor) 

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
torch.manual_seed(100) # sets the seed for generating random numbers
tensor = torch.rand(2,3) # creates a 2x3 matrix with same random values 
print(tensor)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
# using tensor 
tensor = torch.tensor([[1,2,3],[4,5,6]]) # creates a 2x3 matrix with the given values
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


### some other meathodes


In [ ]:
# using arange
tensor = torch.arange(0,10,2) # creates a 1D tensor with values from 0 to 10 with a step of 2
print(tensor)
# using linspace
tensor = torch.linspace(0,10,5) # creates a 1D tensor with 5 values from 0 to 10
print(tensor)
# using full
tensor = torch.full((2,3),7) # creates a 2x3 matrix with all values as 7
print(tensor)

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([[7, 7, 7],
        [7, 7, 7]])


#### Finding the shape of tensor

In [ ]:
x = torch.tensor([1,2,3])
print(x.shape)


torch.Size([3])


In [ ]:
# creating a new tensor with the same shape as x
y = torch.zeros_like(x) # creates a tensor with the same shape as x and all values as 0
print(y)
y = torch.ones_like(x) # creates a tensor with the same shape as x and all values as 1
print(y)
#y = torch.rand_like(x) # creates a tensor with the same shape as x and random values between 0 and 1
#print(y)
y = torch.full_like(x,7) # creates a tensor with the same shape as x and all values as 7
print(y)
#y = torch.eye_like(x) # creates a tensor with the same shape as x and all values as 1 in the diagonal and 0 elsewhere
#print(y)
#y = torch.arange_like(x) # creates a tensor with the same shape as x and values from 0 to the number of elements in x
#print(y)
y = torch.empty_like(x) # creates a tensor with the same shape as x and all values as 1 in the diagonal and 0 elsewhere
print(y)

"""
    # We will see why rand_like, arrange_like and eye_like are not working
    # it is because they generate float values where as x is an integer data type tensor
    # So we explecetly need to tell that we want the float type values
"""

tensor([0, 0, 0])
tensor([1, 1, 1])
tensor([7, 7, 7])
tensor([11704832, 11708864, 11708288])


'\n    # We will see why rand_like, arrange_like and eye_like are not working\n\n    # it is because they generate float values where as x is an integer data type tensor\n\n    # So we explecetly need to tell that we want the float type values\n'

# data type of a tensor

In [ ]:
#
x.dtype

torch.int64

In [ ]:
# how to specify the data type of the tensor
tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float16)
print(tensor, tensor.dtype)
# how to convert the dtype of a tensor
x.to(torch.float32) # don't changes the original tensor
print("x:   ",x,"\n",x.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16) torch.float16
x:    tensor([1, 2, 3]) 
 torch.int64


In [ ]:
x = torch.tensor([1, 2, 3]) # Starts as int64

# Reassign the result to update x
x = x.to(torch.float32)

print("x:   ", x, "\n", x.dtype)
# Output:
# x:    tensor([1., 2., 3.]) 
# torch.float32

x:    tensor([1., 2., 3.]) 
 torch.float32


In [ ]:
# soln to our previous problem
y = torch.rand_like(x, dtype = torch.float32) # we just need to specify the data type
print(y)

tensor([0.1180, 0.1217, 0.7356])


# Operations on tensor

### 1) scalar operation

In [ ]:
# addition
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
print(x + 2)
print( x - 1)
print(x * 2)
print(x / 2)
print(x // 2)
print(x % 2)

tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# operation between two tensor
t1 = torch.full((2,2), 8)
t2 = torch.full((2,2),2)
print(t1)
print(t2)

tensor([[8, 8],
        [8, 8]])
tensor([[2, 2],
        [2, 2]])


In [ ]:
# add 
print(t1 + t2)
# sub 
print(t1 - t2)
# mul
print(t1 * t2)
# div
print(t1/t2)
# power 
print(t1**t2)
# mod 
print(t1%t2)

tensor([[10, 10],
        [10, 10]])
tensor([[6, 6],
        [6, 6]])
tensor([[16, 16],
        [16, 16]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[64, 64],
        [64, 64]])
tensor([[0, 0],
        [0, 0]])


In [ ]:
print("Hello Wprld")